// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using VVUpdaterCore.Models;
//
//    var resources = Resources.FromJson(jsonString);

namespace RGAuth.Models.bdApi
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Resources
    {
        [JsonProperty("resources")]
        public Resource[] ResourcesResources { get; set; }

        [JsonProperty("resources_total")]
        public long ResourcesTotal { get; set; }

        [JsonProperty("links")]
        public ResourcesLinks Links { get; set; }

        [JsonProperty("system_info")]
        public SystemInfo SystemInfo { get; set; }
    }

    public partial class ResourcesLinks
    {
        [JsonProperty("pages")]
        public long Pages { get; set; }

        [JsonProperty("page")]
        public long Page { get; set; }

        [JsonProperty("next")]
        public Uri Next { get; set; }
    }

    public partial class Resource
    {
        [JsonProperty("resource_download_count")]
        public long ResourceDownloadCount { get; set; }

        [JsonProperty("resource_update_date")]
        public long ResourceUpdateDate { get; set; }

        [JsonProperty("resource_rating_count")]
        public long ResourceRatingCount { get; set; }

        [JsonProperty("resource_rating_sum")]
        public long ResourceRatingSum { get; set; }

        [JsonProperty("resource_rating_avg")]
        public double ResourceRatingAvg { get; set; }

        [JsonProperty("resource_rating_weighted")]
        public double ResourceRatingWeighted { get; set; }

        [JsonProperty("resource_category_id")]
        public long ResourceCategoryId { get; set; }

        [JsonProperty("resource_create_date")]
        public long ResourceCreateDate { get; set; }

        [JsonProperty("resource_id")]
        public long ResourceId { get; set; }

        [JsonProperty("resource_description")]
        public string ResourceDescription { get; set; }

        [JsonProperty("resource_title")]
        public string ResourceTitle { get; set; }

        [JsonProperty("creator_user_id")]
        public long CreatorUserId { get; set; }

        [JsonProperty("creator_username")]
        public string CreatorUsername { get; set; }

        [JsonProperty("resource_attachment_count")]
        public long ResourceAttachmentCount { get; set; }

        [JsonProperty("attachments")]
        public ResourceAttachment[] Attachments { get; set; }

        [JsonProperty("fields")]
        public ResourceField[] Fields { get; set; }

        [JsonProperty("resource_has_file")]
        public bool ResourceHasFile { get; set; }

        [JsonProperty("resource_has_url")]
        public bool ResourceHasUrl { get; set; }

        [JsonProperty("resource_is_deleted")]
        public bool ResourceIsDeleted { get; set; }

        [JsonProperty("resource_is_followed")]
        public bool ResourceIsFollowed { get; set; }

        [JsonProperty("resource_is_liked")]
        public bool ResourceIsLiked { get; set; }

        [JsonProperty("resource_is_published")]
        public bool ResourceIsPublished { get; set; }

        [JsonProperty("resource_like_count")]
        public long ResourceLikeCount { get; set; }

        [JsonProperty("resource_rating")]
        public long ResourceRating { get; set; }

        [JsonProperty("resource_tags")]
        public object[] ResourceTags { get; set; }

        [JsonProperty("resource_text")]
        public string ResourceText { get; set; }

        [JsonProperty("resource_text_html")]
        public string ResourceTextHtml { get; set; }

        [JsonProperty("resource_text_plain_text")]
        public string ResourceTextPlainText { get; set; }

        [JsonProperty("resource_version")]
        public string ResourceVersion { get; set; }

        [JsonProperty("links")]
        public ResourceLinks Links { get; set; }

        [JsonProperty("permissions")]
        public ResourcePermissions Permissions { get; set; }
    }

    public partial class ResourceAttachment
    {
        [JsonProperty("attachment_id")]
        public long AttachmentId { get; set; }

        [JsonProperty("filename")]
        public string Filename { get; set; }

        [JsonProperty("attachment_download_count")]
        public long AttachmentDownloadCount { get; set; }

        [JsonProperty("resource_id")]
        public long ResourceId { get; set; }

        [JsonProperty("links")]
        public ResourceAttachmentLinks Links { get; set; }

        [JsonProperty("permissions")]
        public ResourceAttachmentPermissions Permissions { get; set; }
    }

    public partial class ResourceAttachmentLinks
    {
        [JsonProperty("data")]
        public Uri Data { get; set; }

        [JsonProperty("permalink")]
        public Uri Permalink { get; set; }

        [JsonProperty("thumbnail")]
        public Uri Thumbnail { get; set; }

        [JsonProperty("resource")]
        public Uri Resource { get; set; }
    }

    public partial class ResourceAttachmentPermissions
    {
        [JsonProperty("delete")]
        public bool Delete { get; set; }

        [JsonProperty("view")]
        public bool View { get; set; }
    }

    public partial class ResourceField
    {
        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("id")]
        public Id Id { get; set; }

        [JsonProperty("is_multi_choice")]
        public bool IsMultiChoice { get; set; }

        [JsonProperty("position")]
        public Position Position { get; set; }

        [JsonProperty("title")]
        public Title Title { get; set; }

        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
        public string Value { get; set; }

        [JsonProperty("values", NullValueHandling = NullValueHandling.Ignore)]
        public ResourceValueElement[] Values { get; set; }
    }

    public partial class ResourceValueElement
    {
        [JsonProperty("key")]
        public Key Key { get; set; }

        [JsonProperty("value")]
        public ValueEnum Value { get; set; }
    }

    public partial class ResourceLinks
    {
        [JsonProperty("attachments")]
        public Uri Attachments { get; set; }

        [JsonProperty("category")]
        public Uri Category { get; set; }

        [JsonProperty("creator_avatar")]
        public Uri CreatorAvatar { get; set; }

        [JsonProperty("detail")]
        public Uri Detail { get; set; }

        [JsonProperty("followers")]
        public Uri Followers { get; set; }

        [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
        public Uri Icon { get; set; }

        [JsonProperty("likes")]
        public Uri Likes { get; set; }

        [JsonProperty("permalink")]
        public Uri Permalink { get; set; }

        [JsonProperty("ratings")]
        public Uri Ratings { get; set; }

        [JsonProperty("report")]
        public Uri Report { get; set; }

        [JsonProperty("content", NullValueHandling = NullValueHandling.Ignore)]
        public Uri Content { get; set; }

        [JsonProperty("thread")]
        public Uri Thread { get; set; }
    }

    public partial class ResourcePermissions
    {
        [JsonProperty("add_icon")]
        public bool AddIcon { get; set; }

        [JsonProperty("delete")]
        public bool Delete { get; set; }

        [JsonProperty("download")]
        public bool Download { get; set; }

        [JsonProperty("edit")]
        public bool Edit { get; set; }

        [JsonProperty("follow")]
        public bool Follow { get; set; }

        [JsonProperty("like")]
        public bool Like { get; set; }

        [JsonProperty("rate")]
        public bool Rate { get; set; }

        [JsonProperty("report")]
        public bool Report { get; set; }
    }

    public partial class SystemInfo
    {
        [JsonProperty("time")]
        public long Time { get; set; }

        [JsonProperty("visitor_id")]
        public long VisitorId { get; set; }

        [JsonProperty("debug_url")]
        public Uri DebugUrl { get; set; }

        [JsonProperty("client_id")]
        public string ClientId { get; set; }

        [JsonProperty("token_text")]
        public string TokenText { get; set; }

        [JsonProperty("expire_date")]
        public long ExpireDate { get; set; }

        [JsonProperty("scope")]
        public string Scope { get; set; }
    }

    public enum Id { Commands, Copyright, Faq, Included, Instructions, Otherauthors, Requirements, Servertype };

    public enum Position { AboveInfo, BelowInfo, NewTab };

    public enum Title { Commands, FAQ, IncludedInVeryVanilla, Instructions, LicenseName, OtherAuthors, ServerType, SoftwareRequirements };

    public enum Key { Emu, Live, Test, Tlp, Yes };

    public enum ValueEnum { Emu, Live, TestServer, Tlp, Yes };

    public partial class Resources
    {
        public static Resources FromJson(string json) => JsonConvert.DeserializeObject<Resources>(json, RGAuth.Models.bdApi.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Resources self) => JsonConvert.SerializeObject(self, RGAuth.Models.bdApi.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                IdConverter.Singleton,
                PositionConverter.Singleton,
                TitleConverter.Singleton,
                KeyConverter.Singleton,
                ValueEnumConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class IdConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Id) || t == typeof(Id?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "commands":
                    return Id.Commands;
                case "copyright":
                    return Id.Copyright;
                case "faq":
                    return Id.Faq;
                case "included":
                    return Id.Included;
                case "instructions":
                    return Id.Instructions;
                case "otherauthors":
                    return Id.Otherauthors;
                case "requirements":
                    return Id.Requirements;
                case "servertype":
                    return Id.Servertype;
            }
            throw new Exception("Cannot unmarshal type Id");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Id)untypedValue;
            switch (value)
            {
                case Id.Commands:
                    serializer.Serialize(writer, "commands");
                    return;
                case Id.Copyright:
                    serializer.Serialize(writer, "copyright");
                    return;
                case Id.Faq:
                    serializer.Serialize(writer, "faq");
                    return;
                case Id.Included:
                    serializer.Serialize(writer, "included");
                    return;
                case Id.Instructions:
                    serializer.Serialize(writer, "instructions");
                    return;
                case Id.Otherauthors:
                    serializer.Serialize(writer, "otherauthors");
                    return;
                case Id.Requirements:
                    serializer.Serialize(writer, "requirements");
                    return;
                case Id.Servertype:
                    serializer.Serialize(writer, "servertype");
                    return;
            }
            throw new Exception("Cannot marshal type Id");
        }

        public static readonly IdConverter Singleton = new IdConverter();
    }

    internal class PositionConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Position) || t == typeof(Position?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "above_info":
                    return Position.AboveInfo;
                case "below_info":
                    return Position.BelowInfo;
                case "new_tab":
                    return Position.NewTab;
            }
            throw new Exception("Cannot unmarshal type Position");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Position)untypedValue;
            switch (value)
            {
                case Position.AboveInfo:
                    serializer.Serialize(writer, "above_info");
                    return;
                case Position.BelowInfo:
                    serializer.Serialize(writer, "below_info");
                    return;
                case Position.NewTab:
                    serializer.Serialize(writer, "new_tab");
                    return;
            }
            throw new Exception("Cannot marshal type Position");
        }

        public static readonly PositionConverter Singleton = new PositionConverter();
    }

    internal class TitleConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Title) || t == typeof(Title?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Commands":
                    return Title.Commands;
                case "F.A.Q.":
                    return Title.FAQ;
                case "Included in Very Vanilla":
                    return Title.IncludedInVeryVanilla;
                case "Instructions":
                    return Title.Instructions;
                case "License Name":
                    return Title.LicenseName;
                case "Other Authors":
                    return Title.OtherAuthors;
                case "Server Type":
                    return Title.ServerType;
                case "Software Requirements":
                    return Title.SoftwareRequirements;
            }
            throw new Exception("Cannot unmarshal type Title");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Title)untypedValue;
            switch (value)
            {
                case Title.Commands:
                    serializer.Serialize(writer, "Commands");
                    return;
                case Title.FAQ:
                    serializer.Serialize(writer, "F.A.Q.");
                    return;
                case Title.IncludedInVeryVanilla:
                    serializer.Serialize(writer, "Included in Very Vanilla");
                    return;
                case Title.Instructions:
                    serializer.Serialize(writer, "Instructions");
                    return;
                case Title.LicenseName:
                    serializer.Serialize(writer, "License Name");
                    return;
                case Title.OtherAuthors:
                    serializer.Serialize(writer, "Other Authors");
                    return;
                case Title.ServerType:
                    serializer.Serialize(writer, "Server Type");
                    return;
                case Title.SoftwareRequirements:
                    serializer.Serialize(writer, "Software Requirements");
                    return;
            }
            throw new Exception("Cannot marshal type Title");
        }

        public static readonly TitleConverter Singleton = new TitleConverter();
    }

    internal class KeyConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Key) || t == typeof(Key?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "emu":
                    return Key.Emu;
                case "live":
                    return Key.Live;
                case "test":
                    return Key.Test;
                case "tlp":
                    return Key.Tlp;
                case "yes":
                    return Key.Yes;
            }
            throw new Exception("Cannot unmarshal type Key");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Key)untypedValue;
            switch (value)
            {
                case Key.Emu:
                    serializer.Serialize(writer, "emu");
                    return;
                case Key.Live:
                    serializer.Serialize(writer, "live");
                    return;
                case Key.Test:
                    serializer.Serialize(writer, "test");
                    return;
                case Key.Tlp:
                    serializer.Serialize(writer, "tlp");
                    return;
                case Key.Yes:
                    serializer.Serialize(writer, "yes");
                    return;
            }
            throw new Exception("Cannot marshal type Key");
        }

        public static readonly KeyConverter Singleton = new KeyConverter();
    }

    internal class ValueEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(ValueEnum) || t == typeof(ValueEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Emu":
                    return ValueEnum.Emu;
                case "Live":
                    return ValueEnum.Live;
                case "TLP":
                    return ValueEnum.Tlp;
                case "Test Server":
                    return ValueEnum.TestServer;
                case "Yes":
                    return ValueEnum.Yes;
            }
            throw new Exception("Cannot unmarshal type ValueEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (ValueEnum)untypedValue;
            switch (value)
            {
                case ValueEnum.Emu:
                    serializer.Serialize(writer, "Emu");
                    return;
                case ValueEnum.Live:
                    serializer.Serialize(writer, "Live");
                    return;
                case ValueEnum.Tlp:
                    serializer.Serialize(writer, "TLP");
                    return;
                case ValueEnum.TestServer:
                    serializer.Serialize(writer, "Test Server");
                    return;
                case ValueEnum.Yes:
                    serializer.Serialize(writer, "Yes");
                    return;
            }
            throw new Exception("Cannot marshal type ValueEnum");
        }

        public static readonly ValueEnumConverter Singleton = new ValueEnumConverter();
    }
}
