// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using VVUpdaterCore.Models.xfApi;
//
//    var resources = Resources.FromJson(jsonString);

namespace RGAuth.Models.xfApi
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using Newtonsoft.Json.Linq;

    public partial class Resources
    {
        [JsonProperty("resources")]
        public Resource[] ResourcesResources { get; set; }

        [JsonProperty("pagination")]
        public Pagination Pagination { get; set; }
    }

    public partial class Pagination
    {
        [JsonProperty("current_page")]
        public long CurrentPage { get; set; }

        [JsonProperty("last_page")]
        public long LastPage { get; set; }

        [JsonProperty("per_page")]
        public long PerPage { get; set; }

        [JsonProperty("shown")]
        public long Shown { get; set; }

        [JsonProperty("total")]
        public long Total { get; set; }
    }

    public partial class Resource
    {
        [JsonProperty("alt_support_url")]
        public string AltSupportUrl { get; set; }

        [JsonProperty("can_download")]
        public bool CanDownload { get; set; }

        [JsonProperty("can_edit")]
        public bool CanEdit { get; set; }

        [JsonProperty("can_edit_icon")]
        public bool CanEditIcon { get; set; }

        [JsonProperty("can_edit_tags")]
        public bool CanEditTags { get; set; }

        [JsonProperty("can_hard_delete")]
        public bool CanHardDelete { get; set; }

        [JsonProperty("can_soft_delete")]
        public bool CanSoftDelete { get; set; }

        [JsonProperty("can_view_description_attachments")]
        public bool CanViewDescriptionAttachments { get; set; }

        [JsonProperty("Category")]
        public Category Category { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("custom_fields")]
        public ResourceCustomFields CustomFields { get; set; }

        [JsonProperty("download_count")]
        public long DownloadCount { get; set; }

        [JsonProperty("external_url")]
        public string ExternalUrl { get; set; }

        [JsonProperty("icon_url")]
        public Uri IconUrl { get; set; }

        [JsonProperty("is_watching")]
        public bool IsWatching { get; set; }

        [JsonProperty("last_update")]
        public long LastUpdate { get; set; }

        [JsonProperty("prefix", NullValueHandling = NullValueHandling.Ignore)]
        public string Prefix { get; set; }

        [JsonProperty("prefix_id")]
        public long PrefixId { get; set; }

        [JsonProperty("price")]
        public string Price { get; set; }

        [JsonProperty("rating_avg")]
        public double RatingAvg { get; set; }

        [JsonProperty("rating_count")]
        public long RatingCount { get; set; }

        [JsonProperty("rating_weighted")]
        public double RatingWeighted { get; set; }

        [JsonProperty("resource_category_id")]
        public long ResourceCategoryId { get; set; }

        [JsonProperty("resource_date")]
        public long ResourceDate { get; set; }

        [JsonProperty("resource_id")]
        public long ResourceId { get; set; }

        [JsonProperty("resource_state")]
        public ResourceState ResourceState { get; set; }

        [JsonProperty("resource_type")]
        public ResourceType ResourceType { get; set; }

        [JsonProperty("tag_line")]
        public string TagLine { get; set; }

        [JsonProperty("tags")]
        public object[] Tags { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("User")]
        public User User { get; set; }

        [JsonProperty("user_id")]
        public long UserId { get; set; }

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
        public string Version { get; set; }

        [JsonProperty("view_count")]
        public long ViewCount { get; set; }
    }

    public partial class Category
    {
        [JsonProperty("allow_commercial_external")]
        public bool AllowCommercialExternal { get; set; }

        [JsonProperty("allow_external")]
        public bool AllowExternal { get; set; }

        [JsonProperty("allow_fileless")]
        public bool AllowFileless { get; set; }

        [JsonProperty("allow_local")]
        public bool AllowLocal { get; set; }

        [JsonProperty("can_add")]
        public bool CanAdd { get; set; }

        [JsonProperty("can_upload_images")]
        public bool CanUploadImages { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("display_order")]
        public long DisplayOrder { get; set; }

        [JsonProperty("enable_support_url")]
        public bool EnableSupportUrl { get; set; }

        [JsonProperty("enable_versioning")]
        public bool EnableVersioning { get; set; }

        [JsonProperty("last_resource_id")]
        public long LastResourceId { get; set; }

        [JsonProperty("last_resource_title")]
        public string LastResourceTitle { get; set; }

        [JsonProperty("last_update")]
        public long LastUpdate { get; set; }

        [JsonProperty("min_tags")]
        public long MinTags { get; set; }

        [JsonProperty("parent_category_id")]
        public long ParentCategoryId { get; set; }

        //1. Apps & Software
            //3. Public
            //4. Private
        //5. Guides
            //6. Public
            //7. Private
        //8. Macro
            //9. Public
            //10. Private
        //11. Plugin
            //12. Public
            //13. Private
        //14. Testing
            //15. Test posting
            //16. Private
                //22. Temporary Resources
            //21. SCore .db Library
        //19. INIs and Configurations
            //18. KissAssist .ini Library (yes, it's one lower than it's section)
            //20. ModBot .ini Library
            //24. Kiss Outdated .ini
            //24. MuleAssist .ini Library
        //25. Lua
            //26. Public
            //27. Private
        [JsonProperty("resource_category_id")]
        public long ResourceCategoryId { get; set; }

        [JsonProperty("resource_count")]
        public long ResourceCount { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }
    }

    public partial class ResourceCustomFields
    {
        [JsonProperty("commands", NullValueHandling = NullValueHandling.Ignore)]
        public string Commands { get; set; }

        [JsonProperty("otherauthors", NullValueHandling = NullValueHandling.Ignore)]
        public string Otherauthors { get; set; }

        [JsonProperty("servertype")]
        [JsonConverter(typeof(SingleOrArrayConverter<Servertype>))]
        public List<Servertype> Servertype { get; set; }

        [JsonProperty("requirements", NullValueHandling = NullValueHandling.Ignore)]
        public string Requirements { get; set; }

        [JsonProperty("instructions", NullValueHandling = NullValueHandling.Ignore)]
        public string Instructions { get; set; }

        [JsonProperty("faq", NullValueHandling = NullValueHandling.Ignore)]
        public string Faq { get; set; }

        [JsonProperty("included", NullValueHandling = NullValueHandling.Ignore)]
        public Included? Included { get; set; }

        [JsonProperty("copyright", NullValueHandling = NullValueHandling.Ignore)]
        public string Copyright { get; set; }

        [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
        public string Version { get; set; }

        [JsonProperty("class", NullValueHandling = NullValueHandling.Ignore)]
        public string Class { get; set; }

        [JsonProperty("level", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? Level { get; set; }

        [JsonProperty("conditions", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(SingleOrArrayConverter<ConditionsClass>))]
        public List<ConditionsClass> Conditions { get; set; }

        [JsonProperty("expansion", NullValueHandling = NullValueHandling.Ignore)]
        public string Expansion { get; set; }

        [JsonProperty("purpose", NullValueHandling = NullValueHandling.Ignore)]
        public Purpose? Purpose { get; set; }

        [JsonProperty("kisstemplate", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(SingleOrArrayConverter<KisstemplateClass>))]
        public List<KisstemplateClass> Kisstemplate { get; set; }

        [JsonProperty("levelmin", NullValueHandling = NullValueHandling.Ignore)]
        public string Levelmin { get; set; }
    }

    public partial class ConditionsClass
    {
        [JsonProperty("yes", NullValueHandling = NullValueHandling.Ignore)]
        public Included Yes { get; set; }
    }

    public partial class KisstemplateClass
    {
        [JsonProperty("yup")]
        public Yup Yup { get; set; }
    }

    public partial class Servertype
    {
        [JsonProperty("live", NullValueHandling = NullValueHandling.Ignore)]
        public Live? Live { get; set; }

        [JsonProperty("test", NullValueHandling = NullValueHandling.Ignore)]
        public Test? Test { get; set; }

        [JsonProperty("tlp", NullValueHandling = NullValueHandling.Ignore)]
        public Tlp? Tlp { get; set; }

        [JsonProperty("emu", NullValueHandling = NullValueHandling.Ignore)]
        public Emu? Emu { get; set; }
    }

    public partial class User
    {
        [JsonProperty("activity_visible")]
        public bool ActivityVisible { get; set; }

        [JsonProperty("avatar_urls")]
        public AvatarUrls AvatarUrls { get; set; }

        [JsonProperty("can_ban")]
        public bool CanBan { get; set; }

        [JsonProperty("can_converse")]
        public bool CanConverse { get; set; }

        [JsonProperty("can_edit")]
        public bool CanEdit { get; set; }

        [JsonProperty("can_follow")]
        public bool CanFollow { get; set; }

        [JsonProperty("can_ignore")]
        public bool CanIgnore { get; set; }

        [JsonProperty("can_post_profile")]
        public bool CanPostProfile { get; set; }

        [JsonProperty("can_view_profile")]
        public bool CanViewProfile { get; set; }

        [JsonProperty("can_view_profile_posts")]
        public bool CanViewProfilePosts { get; set; }

        [JsonProperty("can_warn")]
        public bool CanWarn { get; set; }

        [JsonProperty("custom_fields")]
        public UserCustomFields CustomFields { get; set; }

        [JsonProperty("custom_title")]
        public string CustomTitle { get; set; }

        [JsonProperty("is_admin")]
        public bool IsAdmin { get; set; }

        [JsonProperty("is_discouraged")]
        public bool IsDiscouraged { get; set; }

        [JsonProperty("is_followed")]
        public bool IsFollowed { get; set; }

        [JsonProperty("is_ignored")]
        public bool IsIgnored { get; set; }

        [JsonProperty("is_moderator")]
        public bool IsModerator { get; set; }

        [JsonProperty("is_staff")]
        public bool IsStaff { get; set; }

        [JsonProperty("is_super_admin")]
        public bool IsSuperAdmin { get; set; }

        [JsonProperty("last_activity")]
        public long LastActivity { get; set; }

        [JsonProperty("location")]
        public string Location { get; set; }

        [JsonProperty("message_count")]
        public long MessageCount { get; set; }

        [JsonProperty("reaction_score")]
        public long ReactionScore { get; set; }

        [JsonProperty("register_date")]
        public long RegisterDate { get; set; }

        [JsonProperty("secondary_group_ids")]
        public long[] SecondaryGroupIds { get; set; }

        [JsonProperty("signature")]
        public string Signature { get; set; }

        [JsonProperty("trophy_points")]
        public long TrophyPoints { get; set; }

        [JsonProperty("user_group_id")]
        public long UserGroupId { get; set; }

        [JsonProperty("user_id")]
        public long UserId { get; set; }

        [JsonProperty("user_state")]
        public UserState UserState { get; set; }

        [JsonProperty("user_title")]
        public string UserTitle { get; set; }

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("visible")]
        public bool Visible { get; set; }

        [JsonProperty("warning_points")]
        public long WarningPoints { get; set; }

        [JsonProperty("website")]
        public string Website { get; set; }

        [JsonProperty("age", NullValueHandling = NullValueHandling.Ignore)]
        public long? Age { get; set; }

        [JsonProperty("dob", NullValueHandling = NullValueHandling.Ignore)]
        public Dob Dob { get; set; }
    }

    public partial class AvatarUrls
    {
        [JsonProperty("o")]
        public Uri O { get; set; }

        [JsonProperty("h")]
        public Uri H { get; set; }

        [JsonProperty("l")]
        public Uri L { get; set; }

        [JsonProperty("m")]
        public Uri M { get; set; }

        [JsonProperty("s")]
        public Uri S { get; set; }
    }

    public partial class UserCustomFields
    {
        [JsonProperty("skype", NullValueHandling = NullValueHandling.Ignore)]
        public string Skype { get; set; }

        [JsonProperty("facebook", NullValueHandling = NullValueHandling.Ignore)]
        public string Facebook { get; set; }

        [JsonProperty("server", NullValueHandling = NullValueHandling.Ignore)]
        public string Server { get; set; }

        [JsonProperty("twitter", NullValueHandling = NullValueHandling.Ignore)]
        public string Twitter { get; set; }
    }

    public partial class Dob
    {
        [JsonProperty("year")]
        public long? Year { get; set; }

        [JsonProperty("month")]
        public long? Month { get; set; }

        [JsonProperty("day")]
        public long? Day { get; set; }
    }

    public enum Included { Empty, Yes };

    public enum Yup { Yup };

    public enum Purpose { Group, Raid, Solo };

    public enum Emu { Emu };

    public enum Live { Live };

    public enum Test { Test };

    public enum Tlp { Tlp };

    public enum ResourceState { Visible, Deleted, Moderated };

    public enum ResourceType { Download, Fileless };

    public enum UserState { Valid, email_bounce };

    public partial class Resources
    {
        public static Resources FromJson(string json) => JsonConvert.DeserializeObject<Resources>(json, RGAuth.Models.xfApi.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Resources self) => JsonConvert.SerializeObject(self, RGAuth.Models.xfApi.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                UserStateConverter.Singleton,
                IncludedConverter.Singleton,
                YupConverter.Singleton,
                PurposeConverter.Singleton,
                EmuConverter.Singleton,
                LiveConverter.Singleton,
                TestConverter.Singleton,
                TlpConverter.Singleton,
                ResourceStateConverter.Singleton,
                ResourceTypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class UserStateConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(UserState) || t == typeof(UserState?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);

            switch(value)
            {
                case "valid":
                    return UserState.Valid;
                case "email_bounce":
                    return UserState.email_bounce;
            }

            throw new Exception("Cannot unmarshal type UserState");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (UserState)untypedValue;

            switch(value)
            {
                case UserState.Valid:
                    serializer.Serialize(writer, "valid");
                    return;
                case UserState.email_bounce:
                    serializer.Serialize(writer, "email_bounce");
                    return;
            }

            throw new Exception("Cannot marshal type UserState");
        }

        public static readonly UserStateConverter Singleton = new UserStateConverter();
    }

    internal class IncludedConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Included) || t == typeof(Included?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "":
                    return Included.Empty;
                case "yes":
                    return Included.Yes;
            }
            throw new Exception("Cannot unmarshal type Included");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Included)untypedValue;
            switch (value)
            {
                case Included.Empty:
                    serializer.Serialize(writer, "");
                    return;
                case Included.Yes:
                    serializer.Serialize(writer, "yes");
                    return;
            }
            throw new Exception("Cannot marshal type Included");
        }

        public static readonly IncludedConverter Singleton = new IncludedConverter();
    }

    internal class YupConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Yup) || t == typeof(Yup?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "yup")
            {
                return Yup.Yup;
            }
            throw new Exception("Cannot unmarshal type Yup");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Yup)untypedValue;
            if (value == Yup.Yup)
            {
                serializer.Serialize(writer, "yup");
                return;
            }
            throw new Exception("Cannot marshal type Yup");
        }

        public static readonly YupConverter Singleton = new YupConverter();
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (string.IsNullOrWhiteSpace(value))
            {
                l = 0;
                return l;
            }
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }

    internal class PurposeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Purpose) || t == typeof(Purpose?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "group":
                    return Purpose.Group;
                case "raid":
                    return Purpose.Raid;
                case "solo":
                    return Purpose.Solo;
            }
            throw new Exception("Cannot unmarshal type Purpose");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Purpose)untypedValue;
            switch (value)
            {
                case Purpose.Group:
                    serializer.Serialize(writer, "group");
                    return;
                case Purpose.Raid:
                    serializer.Serialize(writer, "raid");
                    return;
                case Purpose.Solo:
                    serializer.Serialize(writer, "solo");
                    return;
            }
            throw new Exception("Cannot marshal type Purpose");
        }

        public static readonly PurposeConverter Singleton = new PurposeConverter();
    }

    internal class EmuConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Emu) || t == typeof(Emu?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "emu")
            {
                return Emu.Emu;
            }
            throw new Exception("Cannot unmarshal type Emu");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Emu)untypedValue;
            if (value == Emu.Emu)
            {
                serializer.Serialize(writer, "emu");
                return;
            }
            throw new Exception("Cannot marshal type Emu");
        }

        public static readonly EmuConverter Singleton = new EmuConverter();
    }

    internal class LiveConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Live) || t == typeof(Live?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "live")
            {
                return Live.Live;
            }
            throw new Exception("Cannot unmarshal type Live");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Live)untypedValue;
            if (value == Live.Live)
            {
                serializer.Serialize(writer, "live");
                return;
            }
            throw new Exception("Cannot marshal type Live");
        }

        public static readonly LiveConverter Singleton = new LiveConverter();
    }

    internal class TestConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Test) || t == typeof(Test?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "test")
            {
                return Test.Test;
            }
            throw new Exception("Cannot unmarshal type Test");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Test)untypedValue;
            if (value == Test.Test)
            {
                serializer.Serialize(writer, "test");
                return;
            }
            throw new Exception("Cannot marshal type Test");
        }

        public static readonly TestConverter Singleton = new TestConverter();
    }

    internal class TlpConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Tlp) || t == typeof(Tlp?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "tlp")
            {
                return Tlp.Tlp;
            }
            throw new Exception("Cannot unmarshal type Tlp");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Tlp)untypedValue;
            if (value == Tlp.Tlp)
            {
                serializer.Serialize(writer, "tlp");
                return;
            }
            throw new Exception("Cannot marshal type Tlp");
        }

        public static readonly TlpConverter Singleton = new TlpConverter();
    }

    internal class ResourceStateConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(ResourceState) || t == typeof(ResourceState?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);

            switch (value)
            {
                case "visible":
                    return ResourceState.Visible;
                case "deleted":
                    return ResourceState.Deleted;
                case "moderated":
                    return ResourceState.Moderated;
            }
            throw new Exception("Cannot unmarshal type ResourceState");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (ResourceState)untypedValue;
            switch (value)
            {
                case ResourceState.Visible:
                    serializer.Serialize(writer, "visible");
                    return;
                case ResourceState.Deleted:
                    serializer.Serialize(writer, "deleted");
                    return;
            }

            throw new Exception("Cannot marshal type ResourceState");
        }

        public static readonly ResourceStateConverter Singleton = new ResourceStateConverter();
    }

    internal class ResourceTypeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(ResourceType) || t == typeof(ResourceType?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "download":
                    return ResourceType.Download;
                case "fileless":
                    return ResourceType.Fileless;
            }
            throw new Exception("Cannot unmarshal type ResourceType");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (ResourceType)untypedValue;
            switch (value)
            {
                case ResourceType.Download:
                    serializer.Serialize(writer, "download");
                    return;
                case ResourceType.Fileless:
                    serializer.Serialize(writer, "fileless");
                    return;
            }
            throw new Exception("Cannot marshal type ResourceType");
        }

        public static readonly ResourceTypeConverter Singleton = new ResourceTypeConverter();
    }
}
