// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using VVUpdaterCore.Models.xfApi;
//
//    var resources = Resources.FromJson(jsonString);

namespace RGAuth.Models.xfApi
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using Newtonsoft.Json.Linq;

    public partial class Versions
    {
        [JsonProperty("versions")]
        public RGAuth.Models.xfApi.Version[] VersionsVersions { get; set; }
    }

    public partial class Version
    {
        [JsonProperty("can_download")]
        public bool CanDownload { get; set; }

        [JsonProperty("can_hard_delete")]
        public bool CanHardDelete { get; set; }

        [JsonProperty("can_soft_delete")]
        public bool CanSoftDelete { get; set; }

        [JsonProperty("download_count")]
        public long DownloadCount { get; set; }

        [JsonProperty("files")]
        [JsonConverter(typeof(SingleOrArrayConverter<Files>))]
        public List<Files> FileList { get; set; }

        [JsonProperty("rating_avg")]
        public long RatingAverage { get; set; }

        [JsonProperty("rating_count")]
        public long RatingCount { get; set; }

        [JsonProperty("release_date")]
        public long ReleaseDate { get; set; }

        [JsonProperty("resource_id")]
        public long ResourceId { get; set; }

        [JsonProperty("resource_version")]
        public long ResourceVersion { get; set; }

        [JsonProperty("resource_version_id")]
        public long ResourcesVersionId { get; set; }

        [JsonProperty("version_state")]
        public string VersionState { get; set; }

        [JsonProperty("version_string")]
        public string VersionString { get; set; }
    }

    public partial class Files
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("filename")]
        public string FileName { get; set; }

        [JsonProperty("size")]
        public long Size { get; set; }

        [JsonProperty("download_url")]
        public string DownloadUrl { get; set; }

    }
}